name: Snapshot Validate

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  snapshot-validate:
    name: Validate Snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x bicep
          sudo mv bicep /usr/local/bin/bicep
          bicep --version

      - name: Run Snapshot Validate
        run: bicep snapshot main.bicepparam --mode validate
